targets:
  $default:
    builders:
      drift_dev:
        options:
          data_class_to_companions: false
          skip_verification_code: true
          write_from_json_string_constructor: true
#          store_date_time_values_as_text: true
