name: ezak
description: Unofficial app for viewing schedules of PANS in Nysa

publish_to: 'none'

version: 1.0.7+10

environment:
  sdk: ^3.5.0
#  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any

#  maps_launcher: # this should upgrade package:web dependency
#    git:
#      url: https://github.com/r-durao-pvotal/flutter-maps-launcher.git

  #cupertino_icons: ^1.0.2
#  feature_discovery_fork: ^0.14.2 # this package depends on provider :<
#  flutter_native_splash: ^^2.4.1
  shared_preferences: ^2.0.18
  package_info_plus: ^8.0.2
  flutter_riverpod: ^2.2.0
  json_annotation: ^4.8.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.2
  http: ^1.2.2
  drift: ^2.19.1+1
  drift_flutter: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.6.1
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  build_runner: ^2.3.3
  msix: ^3.16.4
  drift_dev: ^2.19.1

flutter:
  uses-material-design: true

  assets:
    - assets/logotypes/

msix_config:
  display_name: eŻak Nysa
  publisher_display_name: tvn24van
  identity_name: 34396tvn24van.eakNysa
  publisher: CN=3CF0E6F9-DE9C-4363-BF23-6185D8CED471
  msix_version: 1.0.6.0
  capabilities: internetClient
  logo_path: assets/logotypes/logo.png
  languages: pl, en, uk
  store: true