name: ezak
description: Unofficial app for viewing schedules of PANS in Nysa

publish_to: 'none'

version: 2.2.6+19

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any

#  maps_launcher: # this should upgrade package:web dependency
#    git:
#      url: https://github.com/r-durao-pvotal/flutter-maps-launcher.git

  shared_preferences: ^2.0.18
  package_info_plus: ^9.0.0
  flutter_riverpod: ^3.0.0
  json_annotation: ^4.9.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.2
  http: ^1.2.2
  drift: ^2.19.1+1
  drift_flutter: ^0.2.0
  path_provider: ^2.1.5
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.1
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  build_runner: ^2.3.3
  msix: ^3.16.4
  drift_dev: ^2.19.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logotypes/

msix_config:
  display_name: eŻak Nysa
  publisher_display_name: tvn24van
  identity_name: 34396tvn24van.eakNysa
  publisher: CN=3CF0E6F9-DE9C-4363-BF23-6185D8CED471
  msix_version: 1.0.6.0
  capabilities: internetClient
  logo_path: assets/logotypes/logo.png
  languages: pl, en, uk
  store: true